Name:           ros-indigo-schunk-ezn64
Version:        1.3.5
Release:        0%{?dist}
Summary:        ROS schunk_ezn64 package

Group:          Development/Libraries
License:        BSD
URL:            http://www.smartroboticsys.eu/
Source0:        %{name}-%{version}.tar.gz

Requires:       libusbx-devel
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-tf
BuildRequires:  libusbx-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-message-generation
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-tf

%description
Xacro model and usb driver for basic communication with Schunk EZN64 gripper

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Tue Sep 22 2015 Frantisek Durovsky <frantisek.durovsky@smartroboticsys.eu> - 1.3.5-0
- Autogenerated by Bloom

* Tue Sep 22 2015 Frantisek Durovsky <frantisek.durovsky@smartroboticsys.eu> - 1.3.4-0
- Autogenerated by Bloom

* Fri Sep 18 2015 Frantisek Durovsky <frantisek.durovsky@smartroboticsys.eu> - 1.3.3-0
- Autogenerated by Bloom

* Fri Sep 18 2015 Frantisek Durovsky <frantisek.durovsky@smartroboticsys.eu> - 1.3.2-0
- Autogenerated by Bloom

